#!/usr/bin/python3
__author__ = 'Kellan Childers'

import curses
import util
from introscreen import IntroScreen
from conwayscreen import ConwayScreen


def game(stdscr):
    # Ensures a clean visual space.
    stdscr.clear()
    curses.curs_set(False)
    stdscr.nodelay(True)

    # Sets the three main colors for the Conway graph.
    curses.init_pair(1, curses.COLOR_BLUE, curses.COLOR_BLUE)
    curses.init_pair(2, curses.COLOR_WHITE, curses.COLOR_WHITE)
    curses.init_pair(3, curses.COLOR_BLACK, curses.COLOR_BLACK)
    stdscr.bkgd(' ', curses.color_pair(2))

    # Finds the size of the console, then uses that to set up the size of the game.
    console_height, console_width = stdscr.getmaxyx()
    game_height, game_width = util.size_lim(console_height, console_width, 50, 100)

    # Introduces user to game.
    intro_win = IntroScreen(console_height, console_width)
    intro_win.add_intro_text()

    # Creates a pad and Conway graph based on the size of the console.
    # conway should be two smaller than game_pad because game_pad has a border.
    conway = intro_win.start_conway(game_height-2, game_width-2)
    game_pad = ConwayScreen(console_height, console_width, game_height, game_width, conway)

    # Executes Conway's Game of Life repeatedly until user inputs character.
    while True:
        game_pad.take_turn(stdscr)

if __name__ == "__main__":
    # curses.wrapper ensures that program will always fully exit from curses mode if an error occurs.
    curses.wrapper(game)
